# Generated by Django 5.1.2 on 2024-12-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FacebookPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_id", models.CharField(max_length=50, unique=True)),
                ("token", models.CharField(max_length=255)),
                ("agency_name", models.CharField(max_length=255)),
                ("establishment_date", models.CharField(max_length=255)),
                ("deployment_countries", models.CharField(max_length=255)),
                ("agency_location", models.CharField(max_length=255)),
                ("cash_assistance_statement", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Facebook Page",
                "verbose_name_plural": "Facebook Pages",
            },
        ),
    ]
