# Generated by Django 5.1.2 on 2024-12-29 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facebookpage",
            old_name="agency_location",
            new_name="page_name",
        ),
        migrations.RemoveField(
            model_name="facebookpage",
            name="agency_name",
        ),
        migrations.RemoveField(
            model_name="facebookpage",
            name="cash_assistance_statement",
        ),
        migrations.RemoveField(
            model_name="facebookpage",
            name="deployment_countries",
        ),
        migrations.RemoveField(
            model_name="facebookpage",
            name="establishment_date",
        ),
    ]
