# Generated by Django 5.1.2 on 2024-12-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_rename_agency_location_facebookpage_page_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpage",
            name="sheet_id",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
