# Generated by Django 5.1.2 on 2025-01-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0003_facebookpage_sheet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpage",
            name="info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
