# Generated by Django 5.1.3 on 2025-01-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_facebookpage_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpage',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
