# Generated by Django 5.1.2 on 2025-01-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0005_facebookpage_additional_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpage",
            name="sales",
            field=models.TextField(blank=True, null=True),
        ),
    ]
