# Generated by Django 5.1.2 on 2025-02-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0006_facebookpage_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpage",
            name="is_inventory",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="facebookpage",
            name="is_leads",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="facebookpage",
            name="is_pos",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="facebookpage",
            name="is_scheduling",
            field=models.BooleanField(default=True),
        ),
    ]
