# Generated by Django 5.1.2 on 2025-02-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0007_facebookpage_is_inventory_facebookpage_is_leads_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpage",
            name="is_online_selling",
            field=models.BooleanField(default=True),
        ),
    ]
