# Generated by Django 5.1.2 on 2025-02-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0008_facebookpage_is_online_selling"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpage",
            name="is_schedule",
            field=models.BooleanField(default=True),
        ),
    ]
