# Generated by Django 5.1.2 on 2025-04-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0009_facebookpage_is_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpage",
            name="is_schedule",
            field=models.BooleanField(default=True),
        ),
    ]
