# Generated by Django 5.1.2 on 2025-04-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0010_facebookpage_is_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facebookpage",
            name="is_schedule",
        ),
    ]
