# Generated by Django 5.1.2 on 2024-12-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="full_name",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="task",
            field=models.CharField(default="", max_length=255),
        ),
    ]
