# Generated by Django 5.1.2 on 2025-01-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_auto_20250118_1358"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="is_summarized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
