# Generated by Django 5.1.2 on 2025-01-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_chat_is_summarized_userprofile_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="sales",
            field=models.TextField(blank=True, null=True),
        ),
    ]
