# Generated by Django 5.1.2 on 2025-01-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_userprofile_sales"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="sales",
        ),
    ]
