# Generated by Django 5.1.2 on 2025-02-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_remove_userprofile_sales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
