# Generated by Django 5.1.2 on 2025-02-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_alter_userprofile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_leads_complete",
            field=models.BooleanField(default=False),
        ),
    ]
