# Generated by Django 5.1.2 on 2025-04-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_userprofile_is_leads_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="sms",
            field=models.CharField(default="", max_length=15),
            preserve_default=False,
        ),
    ]
