# Generated by Django 5.1.2 on 2025-04-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_userprofile_sms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="sms",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
    ]
