# Generated by Django 4.2.16 on 2024-12-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grammarcheck',
            options={'ordering': ['-id']},
        ),
    ]
