<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-11-27 04:45
=======
# Generated by Django 4.2.16 on 2024-11-17 08:35
>>>>>>> 9e0bbb6 (grammar migrations)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("grammar_check", "0001_initial"),
=======
        ('grammar_check', '0001_initial'),
>>>>>>> 9e0bbb6 (grammar migrations)
    ]

    operations = [
        migrations.AlterModelOptions(
<<<<<<< HEAD
            name="grammarcheck",
            options={"ordering": ["-id"]},
=======
            name='grammarcheck',
            options={'ordering': ['-id']},
>>>>>>> 9e0bbb6 (grammar migrations)
        ),
    ]
