# Generated by Django 5.1.2 on 2025-01-05 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LearnHub", "0002_course_topic_lesson_chathistory_lessonprogress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chathistory",
            name="topic",
        ),
        migrations.AddField(
            model_name="chathistory",
            name="lesson",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="LearnHub.lesson",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
