# Generated by Django 5.1.2 on 2025-01-05 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LearnHub", "0003_remove_chathistory_topic_chathistory_lesson_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessonprogress",
            options={},
        ),
        migrations.RemoveField(
            model_name="lessonprogress",
            name="completed_at",
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="lesson",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="LearnHub.lesson",
            ),
        ),
    ]
