# Generated by Django 5.1.2 on 2025-04-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LearnHub", "0008_htmlcss_phplang"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tableau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_input", models.TextField()),
                ("ai_response", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
